  name: Release Keycloak legacy containers by Andy1
  on:
    workflow_dispatch:
    push:
      tags:
        - '[0-9]+.[0-9]+.[0-9]+'
  concurrency: keycloak-container-legacy-release

  jobs:
    publish:
      if: github.repository == 'andychan516/keycloak-containers'
      runs-on: ubuntu-latest
      strategy:
        matrix:
          include:
            - image: keycloak
              context: server
            - image: keycloak-init-container
              context: keycloak-init-container

      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Container metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: andychan516/${{ matrix.image }}
          tags: |
            type=raw,value={{tag}}-legacy
            type=raw,value=legacy

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
